# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

#volumes:
  # peer2.org1.fp.com:

networks:
  basic-ca:

services:
  root.fp.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    container_name: root.fp.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-rootserver
      - FABRIC_CA_SERVER_CA_NAME=root.fp.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    command: sh -c 'fabric-ca-server start -b admin:adminpw --cfg.affiliations.allowremove  --cfg.identities.allowremove'
   # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile #/etc/hyperledger/fabric-ca-server-config/${PRIVATE_KEY} 
    volumes:
      #- ./crypto-config/peerOrganizations/org1.fp.com/ca/:/etc/hyperledger/fabric-ca-rootserver-config
      - ./ca/rootCA:/etc/hyperledger/fabric-ca-rootserver   
    ports:
      - "7054:7054"
    networks:
      - basic-ca
      
  middle.fp.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    container_name: middle.fp.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-middleserver
      - FABRIC_CA_SERVER_CA_NAME=middle.fp.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    command: sh -c 'fabric-ca-server start -b admin:vsaCNbZGpOtR -u http://admin:adminpw@root.fp.com:7054 -p 7055 --cfg.affiliations.allowremove  --cfg.identities.allowremove'
   # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile #/etc/hyperledger/fabric-ca-server-config/${PRIVATE_KEY} 
    volumes:
      #- ./crypto-config/peerOrganizations/org1.fp.com/ca/:/etc/hyperledger/fabric-ca-middleserver-config
      - ./ca/middleCA:/etc/hyperledger/fabric-ca-middleserver 
    ports:
      - "7055:7055"
    depends_on:
      - root.fp.com
    networks:
      - basic-ca